# Generated by Django 5.2.8 on 2025-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('candidate_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_address', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_city', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_country', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_education', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_portfolio', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_cover_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_resume', models.CharField(blank=True, max_length=255, null=True)),
                ('original_file', models.FileField(upload_to='CVS/')),
                ('full_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
